#define NOFRACTAL        -1
#define MANDEL            0 
#define JULIA             1 
#define NEWTBASIN         2 
#define LAMBDA            3 
#define MANDELFP          4 
#define NEWTON            5 
#define JULIAFP           6 
#define PLASMA            7 
#define LAMBDASINE        8 
#define LAMBDACOS         9 
#define LAMBDAEXP         10
#define TEST              11
#define SIERPINSKI        12
#define BARNSLEYM1        13
#define BARNSLEYJ1        14
#define BARNSLEYM2        15
#define BARNSLEYJ2        16
#define MANDELSINE        17
#define MANDELCOS         18
#define MANDELEXP         19
#define MANDELLAMBDA      20
#define MARKSMANDEL       21
#define MARKSJULIA        22
#define UNITY             23
#define MANDEL4           24
#define JULIA4            25
#define IFS               26
#define IFS3D             27
#define BARNSLEYM3        28
#define BARNSLEYJ3        29
#define DEMM              30
#define DEMJ              31
#define BIFURCATION       32
#define MANDELSINH        33
#define LAMBDASINH        34
#define MANDELCOSH        35
#define LAMBDACOSH        36
#define LMANDELSINE       37
#define LLAMBDASINE       38
#define LMANDELCOS        39
#define LLAMBDACOS        40
#define LMANDELSINH       41
#define LLAMBDASINH       42
#define LMANDELCOSH       43
#define LLAMBDACOSH       44
#define LMANSINZSQRD      45
#define LJULSINZSQRD      46
#define FPMANSINZSQRD     47
#define FPJULSINZSQRD     48
#define LMANDELEXP        49
#define LLAMBDAEXP        50
#define LMANDELZPOWER     51
#define LJULIAZPOWER      52
#define FPMANDELZPOWER    53
#define FPJULIAZPOWER     54
#define FPMANZTOZPLUSZPWR 55
#define FPJULZTOZPLUSZPWR 56
#define LMANSINEXP        57
#define LJULSINEXP        58
#define FPMANSINEXP       59
#define FPJULSINEXP       60
#define FPPOPCORN         61
#define LPOPCORN          62
#define FPLORENZ          63
#define LLORENZ           64
#define LLORENZ3D         65
#define MPNEWTON          66 
#define MPNEWTBASIN       67 
#define COMPLEXNEWTON     68
#define COMPLEXBASIN      69
/* DEFINITIONS PRIOR TO THIS POINT ARE FROZEN BY THE VERSION 11.0 RELEASE! */

#define COMPLEXMARKSMAND  70
#define COMPLEXMARKSJUL   71
#define FORMULA           72
#define FFORMULA          73
#define SIERPINSKIFP      74
#define LAMBDAFP          75
#define BARNSLEYM1FP      76
#define BARNSLEYJ1FP      77
#define BARNSLEYM2FP      78
#define BARNSLEYJ2FP      79
#define BARNSLEYM3FP      80
#define BARNSLEYJ3FP      81
#define MANDELLAMBDAFP    82
#define JULIBROT          83

/* DEFINITIONS PRIOR TO THIS POINT ARE FROZEN BY THE VERSION 12.0 RELEASE! */
#define FPLORENZ3D        84
#define LROSSLER          85
#define FPROSSLER         86
#define LHENON            87
#define FPHENON           88
#define FPPICKOVER        89
#define FPGINGERBREAD     90
#define DIFFUSION         91
#define UNITYFP           92


#define NEWTONDEGREELIMIT  100
