
/*
 * HELPDEFS.H
 *
 * Contains #defines for help.
 *
 * Generated by HC from: help.src
 *
 */


/* current help file version */

#define HELP_VERSION                     100


/* labels */

#define HELP_INDEX                         0        /* index */
#define ANTCOMMANDS                        1
#define HELP3D                             2
#define HELP3DFILL                         3
#define HELP3DFRACT                        4
#define HELP3DGLASSES                      5
#define HELP3DLIGHT                        6
#define HELP3DMODE                         7
#define HELP3DOVLY                         8
#define HELP3DPARMS                        9
#define HELPBROWSE                        10
#define HELPBRWSPARMS                     11
#define HELPCOLORMAP                      12
#define HELPCOMMANDS                      13
#define HELPCOORDS                        14
#define HELPCYCLING                       15
#define HELPFRACTALS                      16
#define HELPLOADFILE                      17
#define HELPMAIN                          18
#define HELPMENU                          19
#define HELPPARMFILE                      20
#define HELPRDS                           21
#define HELPSAVEREST                      22
#define HELPSTARFLD                       23
#define HELPVIDSEL                        24
#define HELPVIEW                          25
#define HELPXHAIR                         26
#define HELPXOPTS                         27
#define HELPYOPTS                         28
#define HELPZOOM                          29
#define HELP_JIIM                         30
#define HELP_ORBITS                       31
#define HF_ANT                            32
#define HF_BARNSJ1                        33
#define HF_BARNSJ2                        34
#define HF_BARNSJ3                        35
#define HF_BARNSM1                        36
#define HF_BARNSM2                        37
#define HF_BARNSM3                        38
#define HF_BIFEQSINPI                     39
#define HF_BIFLAMBDA                      40
#define HF_BIFMAY                         41
#define HF_BIFPLUSSINPI                   42
#define HF_BIFSTEWART                     43
#define HF_BIFURCATION                    44
#define HF_CELLULAR                       45
#define HF_CHIP                           46
#define HF_CIRCLE                         47
#define HF_CMPLXMARKSJUL                  48
#define HF_CMPLXMARKSMAND                 49
#define HF_COMPLEXNEWT                    50
#define HF_DIFFUS                         51
#define HF_DYNAM                          52
#define HF_FNPLUSFN                       53
#define HF_FNPLUSFNPIX                    54
#define HF_FNTIMESFN                      55
#define HF_FNXZPLUSZ                      56
#define HF_FNZTIMESZ                      57
#define HF_FROTH                          58
#define HF_GINGER                         59
#define HF_HALLEY                         60
#define HF_HENON                          61
#define HF_HOPALONG                       62
#define HF_HYPERC                         63
#define HF_HYPERCJ                        64
#define HF_ICON                           65
#define HF_INVERSE                        66
#define HF_JULFNPLUSEXP                   67
#define HF_JULFNPLUSZSQRD                 68
#define HF_JULIA                          69
#define HF_JULIA4                         70
#define HF_JULIAFNFN                      71
#define HF_JULZPOWER                      72
#define HF_JULZZPWR                       73
#define HF_KAM                            74
#define HF_LAMBDA                         75
#define HF_LAMBDAFN                       76
#define HF_LAMBDAFNFN                     77
#define HF_LORENZ                         78
#define HF_LORENZ3D1                      79
#define HF_LORENZ3D3                      80
#define HF_LORENZ3D4                      81
#define HF_MAGJ1                          82
#define HF_MAGJ2                          83
#define HF_MAGM1                          84
#define HF_MAGM2                          85
#define HF_MANDEL                         86
#define HF_MANDEL4                        87
#define HF_MANDELCLOUD                    88
#define HF_MANDELFNFN                     89
#define HF_MANDFN                         90
#define HF_MANDFNPLUSEXP                  91
#define HF_MANDFNPLUSZSQRD                92
#define HF_MANDPHOENIX                    93
#define HF_MANDPHOENIXCPLX                94
#define HF_MANLAMFNFN                     95
#define HF_MANOWAR                        96
#define HF_MANOWARJ                       97
#define HF_MANZPOWER                      98
#define HF_MANZZPWR                       99
#define HF_MARKSJULIA                    100
#define HF_MARKSMAND                     101
#define HF_MARKSMANDPWR                  102
#define HF_MARTIN                        103
#define HF_MLAMBDA                       104
#define HF_NEWT                          105
#define HF_NEWTBAS                       106
#define HF_PHOENIX                       107
#define HF_PHOENIXCPLX                   108
#define HF_PICKOVER                      109
#define HF_PLASMA                        110
#define HF_POPCJUL                       111
#define HF_POPCORN                       112
#define HF_QUADRUPTWO                    113
#define HF_QUAT                          114
#define HF_QUATJ                         115
#define HF_ROSS                          116
#define HF_SIER                          117
#define HF_SPIDER                        118
#define HF_SQRFN                         119
#define HF_SQROVFN                       120
#define HF_TEST                          121
#define HF_TETRATE                       122
#define HF_THREEPLY                      123
#define HF_TIMSERR                       124
#define HF_UNITY                         125
#define HT_ANT                           126
#define HT_BARNS                         127
#define HT_BIF                           128
#define HT_CELLULAR                      129
#define HT_CIRCLE                        130
#define HT_DIFFUS                        131
#define HT_DYNAM                         132
#define HT_FNORFN                        133
#define HT_FORMULA                       134
#define HT_FROTH                         135
#define HT_GINGER                        136
#define HT_HALLEY                        137
#define HT_HENON                         138
#define HT_HYPERC                        139
#define HT_ICON                          140
#define HT_IFS                           141
#define HT_INVERSE                       142
#define HT_JULIA                         143
#define HT_JULIBROT                      144
#define HT_KAM                           145
#define HT_LAMBDA                        146
#define HT_LAMBDAFN                      147
#define HT_LORENZ                        148
#define HT_LSYS                          149
#define HT_LYAPUNOV                      150
#define HT_MAGNET                        151
#define HT_MANDEL                        152
#define HT_MANDELCLOUD                   153
#define HT_MANDFN                        154
#define HT_MANDJUL4                      155
#define HT_MARKS                         156
#define HT_MARTIN                        157
#define HT_MLAMBDA                       158
#define HT_NEWT                          159
#define HT_NEWTBAS                       160
#define HT_NEWTCMPLX                     161
#define HT_PHOENIX                       162
#define HT_PICK                          163
#define HT_PICKMJ                        164
#define HT_PLASMA                        165
#define HT_POPCORN                       166
#define HT_QUAT                          167
#define HT_ROSS                          168
#define HT_SCOTSKIN                      169
#define HT_SIER                          170
#define HT_TEST                          171
#define HT_UNITY                         172
#define INTRO_AUTHORS                    173
#define INTRO_CREDITS                    174
#define RDSKEYS                          175


